vich_uploader:
    db_driver: orm

    mappings:
        poster_file:
            uri_prefix: /images/posters
            upload_destination: '%upload_directory%'

            delete_on_update: true
            namer:
                service: Vich\UploaderBundle\Naming\SmartUniqueNamer